# Generated by Django 5.0.2 on 2024-08-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='directions',
            field=models.JSONField(blank=True, default=list),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.JSONField(blank=True, default=list),
            preserve_default=False,
        ),
    ]
