# Generated by Django 5.0.2 on 2024-09-07 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_recipe_directions_recipe_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
